### ISSUE TITLE
web Accessible Resources

### ISSUE THREAD

**Issue by mskian** [sidvishnoi/facebook-crap-remover#1]
I found this on `manifest.json`

```json
"web_accessible_resources": [
    "inject.js"
  ]
```
why we need this ? there is no `inject.js` file

**Comment by sidvishnoi** [comment]
Good catch. I added inject.js earlier and later forgot to remove it from manifest. Harmless though. Feel free to send a PR, I don't really maintain this project.

**Comment by mskian** [comment]
Sure I will Send

I Spot this error too `Uncaught Error: Extension context invalidated.`
Error Highlighter was point this line from the file `extension.js`

```js
chrome.storage.local.get({ count: 0 }, res => {
```
After adding this Below Function not getting this error

```js
if(typeof chrome.app.isInstalled!=='undefined'){
        chrome.storage.local.get({ count: 0 }, res => {
          chrome.storage.local.set({ count: res.count + 1 });
        });
       }
```

**Comment by mskian** [comment]
@sidvishnoi any idea about the errors I mentioned above

**Comment by sidvishnoi** [comment]
Not yet. I'll have to check it. I can't reproduce it locally though.

**Comment by mskian** [comment]
hm Login Facebook use it Max 5 to 10 mins
after that log out it and goto extension page and check it 
I am not getting this continuously but sometimes I spot this 
https://stackoverflow.com/questions/53939205/how-to-avoid-extension-context-invalidated-errors-when-messaging-after-an-exte

**Comment by mskian** [comment]
It removes the non-registered Keywords too

example:

if I provide word `got` on the keyword section for hiding the post which having the word `got`
but it hides the sentence with having the word `got` example post with the word the `gotify`

**Comment by sidvishnoi** [comment]
Looks like I would revert https://github.com/sidvishnoi/facebook-crap-remover/commit/52d46f887bea9c6be4197b6d5258c9faa5292c14. (It was working fine for my usage, and I tried to keep it really simple. It was 20min-30min work)
Thanks for reporting. Feels good when someone else is also using your stuff 😅

**Comment by mskian** [comment]
@sidvishnoi Thanks for the Update bro :100:
